spring.application.name=microUsuarios

# ======================================================
# ? SERVER CONFIG
# ======================================================
server.port=5000

# ======================================================
# ?? DATASOURCE (POSTGRESQL - NEON)
# ======================================================
spring.datasource.url=jdbc:postgresql://ep-fancy-haze-amupuyi4-pooler.c-5.us-east-1.aws.neon.tech:5432/usuariosdb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mbAVYt0LR8zd
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================================================
# ? JPA / HIBERNATE
# ======================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ======================================================
# ? SECURITY - AUTH0
# ======================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-vq65v0hxzkvb44f0.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://BioHouse.com

# ======================================================
# ? LOGGING
# ======================================================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.co.edu.unicauca.microUsuarios=DEBUG